#!/bin/sh
# configure-alsa.sh — Check/fix ALSA-on-FreeBSD (OSS wrapper) configuration
# CLI mode: reports package and config status, fixes issues
# TUI mode: interactive editor for .asoundrc via bsddialog
#
# Usage:
#   ./configure-alsa.sh             — Check and prompt to fix
#   ./configure-alsa.sh --auto      — Apply all fixes without prompting
#   ./configure-alsa.sh --dry-run   — Check only, no changes
#   ./configure-alsa.sh --tui       — Launch interactive settings editor
#   ./configure-alsa.sh --help      — Show help

set -u

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "${SCRIPT_DIR}/lib/common.sh"

MODE="interactive"
ASOUNDRC="${HOME}/.asoundrc"
ASOUND_SYS="/usr/local/etc/asound.conf"

case "${1:-}" in
    --auto)    MODE="auto" ;;
    --dry-run) MODE="dryrun" ;;
    --tui)     MODE="tui" ;;
    --help|-h)
        cat <<EOF
configure-alsa.sh — ALSA configuration for FreeBSD

FreeBSD has no native ALSA kernel layer. ALSA here is provided by
alsa-lib + alsa-plugins which wrap ALSA calls to OSS. This script
ensures the wrapper is installed and configured to use virtual_oss.

CLI mode (default):
  Checks packages, .asoundrc / asound.conf, and OSS device mapping.

TUI mode (--tui):
  Interactive editor for PCM device, mixer device, and plugin options.

Options:
  --auto      Apply all fixes without prompting
  --dry-run   Check only, no changes
  --tui       Launch interactive settings editor
  --help      Show this help
EOF
        exit 0
        ;;
esac

# ── Helpers ─────────────────────────────────────────────────────────────────
ask_yes() {
    if [ "$MODE" = "auto" ]; then return 0; fi
    if [ "$MODE" = "dryrun" ]; then return 1; fi
    printf "  %s [y/N] " "$1"
    read -r _ans
    case "$_ans" in [Yy]*) return 0 ;; *) return 1 ;; esac
}

# Detect virtual_oss virtual device
detect_voss_device() {
    _pid=$(pgrep -x virtual_oss 2>/dev/null || true)
    if [ -n "$_pid" ]; then
        _vd=$(ps -ww -p "$(echo "$_pid" | head -1)" -o args= 2>/dev/null \
            | grep -oE '\-d [^ ]+' | awk '{print $2}' | head -1)
        [ -n "$_vd" ] && echo "/dev/${_vd}" && return
    fi
    # Fall back to rc.conf
    _configs=$(sysrc -n virtual_oss_configs 2>/dev/null || echo "")
    for _c in $_configs; do
        _val=$(sysrc -n "virtual_oss_${_c}" 2>/dev/null || true)
        _vd=$(echo "$_val" | grep -oE '\-d [^ ]+' | awk '{print $2}' | head -1)
        [ -n "$_vd" ] && echo "/dev/${_vd}" && return
    done
    echo "/dev/dsp"
}

# Parse asoundrc: extract device from a pcm or ctl block
asoundrc_get_device() {
    _file=$1
    _block=$2  # "pcm" or "ctl"
    [ ! -f "$_file" ] && return
    # Simple parser: find "type oss" block and its device line
    awk -v block="${_block}" '
        $0 ~ block "\\." { in_block=1 }
        in_block && /device/ { gsub(/.*device[[:space:]]+/, ""); gsub(/[[:space:]]*$/, ""); print; exit }
        in_block && /^}/ { in_block=0 }
    ' "$_file" 2>/dev/null
}

# Parse asoundrc: extract type from a pcm or ctl block
asoundrc_get_type() {
    _file=$1
    _block=$2
    [ ! -f "$_file" ] && return
    awk -v block="${_block}" '
        $0 ~ block "\\." { in_block=1 }
        in_block && /type/ { gsub(/.*type[[:space:]]+/, ""); gsub(/[[:space:]]*$/, ""); print; exit }
        in_block && /^}/ { in_block=0 }
    ' "$_file" 2>/dev/null
}

# Write a complete asoundrc
write_asoundrc() {
    _file=$1
    _pcm_dev=$2
    _mixer_dev=$3
    cat > "$_file" <<EOF
# Generated by configure-alsa.sh
# ALSA-to-OSS wrapper for FreeBSD + virtual_oss

pcm.!default {
    type oss
    device ${_pcm_dev}
}

ctl.!default {
    type oss
    device ${_mixer_dev}
}
EOF
}

# ════════════════════════════════════════════════════════════════════════════
#  CLI MODE
# ════════════════════════════════════════════════════════════════════════════
cli_mode() {
    ISSUES=0

    section "ALSA — Packages"

    _missing=""
    for _pkg in alsa-lib alsa-plugins; do
        if pkg info "$_pkg" >/dev/null 2>&1; then
            ok "${_pkg} installed"
        else
            fail "${_pkg} not installed"
            _missing="${_missing} ${_pkg}"
            ISSUES=$((ISSUES + 1))
        fi
    done

    if pkg info alsa-utils >/dev/null 2>&1; then
        ok "alsa-utils installed"
    else
        info "alsa-utils not installed (optional, provides aplay/amixer)"
    fi

    if [ -n "$_missing" ]; then
        if ask_yes "Install missing packages:${_missing}?"; then
            pkg install -y $_missing 2>&1 | tail -1
            ok "Installed"
        fi
    fi

    # ── Config files ────────────────────────────────────────────────────────
    section "ALSA — Configuration"

    _voss_dev=$(detect_voss_device)
    info "Detected virtual_oss device: ${_voss_dev}"

    # Effective config: user overrides system
    _effective=""
    if [ -f "$ASOUNDRC" ]; then
        _effective="$ASOUNDRC"
        ok "User config exists: ${ASOUNDRC}"
    elif [ -f "$ASOUND_SYS" ]; then
        _effective="$ASOUND_SYS"
        ok "System config exists: ${ASOUND_SYS}"
    fi

    if [ -f "$ASOUND_SYS" ] && [ -f "$ASOUNDRC" ]; then
        info "Both exist — user ${ASOUNDRC} takes precedence"
    fi

    if [ -z "$_effective" ]; then
        fail "No .asoundrc or asound.conf found"
        ISSUES=$((ISSUES + 1))
        info "ALSA apps may not find the correct OSS device"

        if ask_yes "Create ${ASOUNDRC} pointing to ${_voss_dev}?"; then
            write_asoundrc "$ASOUNDRC" "$_voss_dev" "/dev/mixer"
            ok "Created ${ASOUNDRC}"
            _effective="$ASOUNDRC"
        fi
    fi

    # ── Validate content ────────────────────────────────────────────────────
    if [ -n "$_effective" ]; then
        section "ALSA — Config Validation"

        # PCM type
        _pcm_type=$(asoundrc_get_type "$_effective" "pcm")
        if [ "$_pcm_type" = "oss" ]; then
            ok "PCM type: oss"
        elif [ -n "$_pcm_type" ]; then
            warn "PCM type: ${_pcm_type} (expected 'oss' on FreeBSD)"
            ISSUES=$((ISSUES + 1))
        else
            warn "No PCM default block found"
            ISSUES=$((ISSUES + 1))
        fi

        # PCM device
        _pcm_dev=$(asoundrc_get_device "$_effective" "pcm")
        if [ -n "$_pcm_dev" ]; then
            ok "PCM device: ${_pcm_dev}"
            if [ "$_pcm_dev" != "$_voss_dev" ]; then
                warn "  Does not match detected virtual_oss device (${_voss_dev})"
                ISSUES=$((ISSUES + 1))
                if ask_yes "Update PCM device to ${_voss_dev}?"; then
                    _mixer_dev=$(asoundrc_get_device "$_effective" "ctl")
                    [ -z "$_mixer_dev" ] && _mixer_dev="/dev/mixer"
                    write_asoundrc "$_effective" "$_voss_dev" "$_mixer_dev"
                    ok "Updated"
                fi
            fi
        else
            warn "No PCM device path found"
            ISSUES=$((ISSUES + 1))
        fi

        # CTL type
        _ctl_type=$(asoundrc_get_type "$_effective" "ctl")
        if [ "$_ctl_type" = "oss" ]; then
            ok "CTL type: oss"
        elif [ -n "$_ctl_type" ]; then
            warn "CTL type: ${_ctl_type} (expected 'oss')"
            ISSUES=$((ISSUES + 1))
        else
            warn "No CTL default block found"
            ISSUES=$((ISSUES + 1))
        fi

        # CTL device
        _ctl_dev=$(asoundrc_get_device "$_effective" "ctl")
        if [ -n "$_ctl_dev" ]; then
            ok "CTL device: ${_ctl_dev}"
        else
            warn "No CTL device path found"
            ISSUES=$((ISSUES + 1))
        fi
    fi

    # ── Quick test ──────────────────────────────────────────────────────────
    section "ALSA — Device Test"

    if command -v aplay >/dev/null 2>&1; then
        _devs=$(aplay -l 2>/dev/null || true)
        if [ -n "$_devs" ]; then
            ok "aplay can list devices"
        else
            warn "aplay -l returned empty (may be normal on FreeBSD OSS wrapper)"
        fi
    else
        info "aplay not available (install alsa-utils for testing)"
    fi

    # Check the OSS device exists
    if [ -n "$_voss_dev" ] && [ -e "$_voss_dev" ]; then
        ok "OSS device ${_voss_dev} exists"
    elif [ -n "$_voss_dev" ]; then
        fail "OSS device ${_voss_dev} does not exist"
        info "Is virtual_oss running?"
        ISSUES=$((ISSUES + 1))
    fi

    # ── Summary ─────────────────────────────────────────────────────────────
    printf "\n"
    if [ "$ISSUES" -eq 0 ]; then
        ok "All checks passed."
    else
        info "${ISSUES} issue(s) found."
        [ "$MODE" = "dryrun" ] && info "Run without --dry-run to fix."
    fi
}

# ════════════════════════════════════════════════════════════════════════════
#  TUI MODE
# ════════════════════════════════════════════════════════════════════════════
tui_mode() {
    if ! command -v bsddialog >/dev/null 2>&1; then
        printf "Error: bsddialog not found. Install it or use FreeBSD 14+.\n" >&2
        exit 1
    fi

    _BT="ALSA Configuration — FreeBSD $(uname -r)"
    _target="$ASOUNDRC"

    while true; do
        # Read current values
        _pcm_dev=""
        _ctl_dev=""
        _pcm_type=""
        _ctl_type=""
        if [ -f "$_target" ]; then
            _pcm_type=$(asoundrc_get_type "$_target" "pcm")
            _pcm_dev=$(asoundrc_get_device "$_target" "pcm")
            _ctl_type=$(asoundrc_get_type "$_target" "ctl")
            _ctl_dev=$(asoundrc_get_device "$_target" "ctl")
        fi
        [ -z "$_pcm_type" ] && _pcm_type="(not set)"
        [ -z "$_pcm_dev" ] && _pcm_dev="(not set)"
        [ -z "$_ctl_type" ] && _ctl_type="(not set)"
        [ -z "$_ctl_dev" ] && _ctl_dev="(not set)"

        _exists="exists"
        [ ! -f "$_target" ] && _exists="does not exist"

        _choice=$(bsddialog \
            --backtitle "$_BT" \
            --title "ALSA Settings" \
            --ok-label "Edit" \
            --cancel-label "Exit" \
            --menu "File: ${_target} (${_exists})" 16 65 6 \
            pcm_dev   "PCM device: ${_pcm_dev}" \
            ctl_dev   "Mixer device: ${_ctl_dev}" \
            view      "View current .asoundrc" \
            reset     "Reset to defaults for virtual_oss" \
            3>&1 1>&2 2>&3) || return

        case "$_choice" in
            pcm_dev)
                _new=$(_select_oss_device "$_BT" "PCM (playback) device:" "$_pcm_dev") || continue
                _cur_ctl=$(asoundrc_get_device "$_target" "ctl")
                [ -z "$_cur_ctl" ] && _cur_ctl="/dev/mixer"
                write_asoundrc "$_target" "$_new" "$_cur_ctl"
                ;;
            ctl_dev)
                _new=$(_select_mixer_device "$_BT" "$_ctl_dev") || continue
                _cur_pcm=$(asoundrc_get_device "$_target" "pcm")
                [ -z "$_cur_pcm" ] && _cur_pcm="/dev/dsp"
                write_asoundrc "$_target" "$_cur_pcm" "$_new"
                ;;
            view)
                if [ -f "$_target" ]; then
                    bsddialog --backtitle "$_BT" --title "$_target" \
                        --textbox "$_target" 18 65
                else
                    bsddialog --backtitle "$_BT" --title "Not Found" \
                        --msgbox "${_target} does not exist yet." 7 45
                fi
                ;;
            reset)
                _vdev=$(detect_voss_device)
                bsddialog --backtitle "$_BT" --title "Reset" \
                    --yesno "Reset ${_target} to defaults?\n\nPCM device: ${_vdev}\nMixer: /dev/mixer" 10 50 || continue
                write_asoundrc "$_target" "$_vdev" "/dev/mixer"
                bsddialog --backtitle "$_BT" --title "Done" \
                    --msgbox "Config reset." 7 35
                ;;
        esac
    done
}

_select_oss_device() {
    _bt=$1
    _title=$2
    _default=$3

    _items=""
    # List available /dev/dsp* nodes
    for _d in /dev/dsp*; do
        [ -e "$_d" ] || continue
        case "$_d" in *.ctl*|*.wav*) continue ;; esac
        _unit=$(echo "$_d" | sed 's|/dev/dsp||')
        _desc=""
        if [ -n "$_unit" ] && echo "$_unit" | grep -qE '^[0-9]+$'; then
            _desc=$(sysctl -n "dev.pcm.${_unit}.%desc" 2>/dev/null || echo "")
        fi
        [ -z "$_desc" ] && _desc="OSS device"
        _items="${_items} ${_d} \"${_desc}\""
    done

    [ -z "$_items" ] && _items="/dev/dsp \"Default OSS device\""

    eval bsddialog \
        --backtitle "\"${_bt}\"" \
        --title "\"${_title}\"" \
        --default-item "\"${_default}\"" \
        --menu "\"Select OSS device for ALSA PCM:\"" 16 65 8 \
        ${_items} \
        3>&1 1>&2 2>&3
}

_select_mixer_device() {
    _bt=$1
    _default=$2

    _items=""
    for _m in /dev/mixer*; do
        [ -e "$_m" ] || continue
        _items="${_items} ${_m} \"OSS mixer\""
    done
    [ -z "$_items" ] && _items="/dev/mixer \"Default mixer\""

    eval bsddialog \
        --backtitle "\"${_bt}\"" \
        --title "\"Mixer Device\"" \
        --default-item "\"${_default}\"" \
        --menu "\"Select OSS mixer for ALSA CTL:\"" 14 55 6 \
        ${_items} \
        3>&1 1>&2 2>&3
}

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#                              MAIN
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

if [ "$MODE" = "tui" ]; then
    tui_mode
else
    cli_mode
fi
