#!/bin/sh
# configure-pipewire.sh — Check/fix PipeWire for FreeBSD (no systemd)
# CLI mode: reports packages, env vars, config, process status, fixes issues
# TUI mode: interactive editor for drop-in settings via bsddialog
#
# Usage:
#   ./configure-pipewire.sh             — Check and prompt to fix
#   ./configure-pipewire.sh --auto      — Apply all fixes without prompting
#   ./configure-pipewire.sh --dry-run   — Check only, no changes
#   ./configure-pipewire.sh --tui       — Launch interactive settings editor
#   ./configure-pipewire.sh --help      — Show help

set -u

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "${SCRIPT_DIR}/lib/common.sh"

MODE="interactive"
PW_SYS_CONF="/usr/local/etc/pipewire"
PW_SHARE_CONF="/usr/local/share/pipewire"
PW_USER_DIR="${HOME}/.config/pipewire"
PW_DROPIN_DIR="${PW_USER_DIR}/pipewire.conf.d"
PW_LATENCY_CONF="${PW_DROPIN_DIR}/latency.conf"
PW_USER_UID="$(id -u)"
XDG_DIR="/run/user/${PW_USER_UID}"

PROFILE_FILES="${HOME}/.profile ${HOME}/.xinitrc ${HOME}/.xprofile ${HOME}/.zprofile ${HOME}/.bash_profile ${HOME}/.login_conf"

case "${1:-}" in
    --auto)    MODE="auto" ;;
    --dry-run) MODE="dryrun" ;;
    --tui)     MODE="tui" ;;
    --help|-h)
        cat <<EOF
configure-pipewire.sh — PipeWire configuration for FreeBSD

PipeWire on FreeBSD lacks systemd integration. This script handles
the extra wiring needed: environment variables, runtime directories,
daemon startup, and drop-in configuration.

CLI mode (default):
  Checks packages, XDG_RUNTIME_DIR, DBUS env, process status,
  drop-in configs, ALSA plugin, and profile scripts.

TUI mode (--tui):
  Interactive editor for latency/quantum settings, clock rate,
  and session startup configuration.

Options:
  --auto      Apply all fixes without prompting
  --dry-run   Check only, no changes
  --tui       Launch interactive settings editor
  --help      Show this help
EOF
        exit 0
        ;;
esac

# ── Helpers ─────────────────────────────────────────────────────────────────
ask_yes() {
    if [ "$MODE" = "auto" ]; then return 0; fi
    if [ "$MODE" = "dryrun" ]; then return 1; fi
    printf "  %s [y/N] " "$1"
    read -r _ans
    case "$_ans" in [Yy]*) return 0 ;; *) return 1 ;; esac
}

# Read a SPA-JSON property from a drop-in conf
pw_dropin_get() {
    _file=$1
    _key=$2
    [ ! -f "$_file" ] && return
    grep -oE "${_key}[[:space:]]*=[[:space:]]*[0-9]+" "$_file" 2>/dev/null \
        | head -1 | grep -oE '[0-9]+$'
}

# Write the latency drop-in
pw_write_latency_conf() {
    _quantum=$1
    _min=$2
    _max=$3
    _rate=$4
    mkdir -p "$PW_DROPIN_DIR"
    cat > "$PW_LATENCY_CONF" <<EOF
# Generated by configure-pipewire.sh
# PipeWire latency/quantum settings for FreeBSD
context.properties = {
    default.clock.quantum = ${_quantum}
    default.clock.min-quantum = ${_min}
    default.clock.max-quantum = ${_max}
    default.clock.rate = ${_rate}
}
EOF
}

# Check if a profile file has required env exports
profile_has_xdg() {
    for _f in $PROFILE_FILES; do
        [ -f "$_f" ] && grep -q 'XDG_RUNTIME_DIR' "$_f" 2>/dev/null && echo "$_f" && return
    done
    return 1
}

profile_has_dbus() {
    for _f in $PROFILE_FILES; do
        [ -f "$_f" ] && grep -q 'DBUS_SESSION_BUS_ADDRESS' "$_f" 2>/dev/null && echo "$_f" && return
    done
    return 1
}

# Generate the env block for profile
env_block() {
    cat <<'ENVEOF'

# PipeWire required environment (FreeBSD — no systemd)
export XDG_RUNTIME_DIR=/run/user/$(id -u)
export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus
ENVEOF
}

# Generate the daemon startup block
startup_block() {
    cat <<'STARTEOF'

# Start PipeWire session (FreeBSD — no systemd)
if command -v pipewire >/dev/null 2>&1; then
    pgrep -x pipewire >/dev/null 2>&1 || daemon -f pipewire
    pgrep -x pipewire-pulse >/dev/null 2>&1 || daemon -f pipewire-pulse
    pgrep -x wireplumber >/dev/null 2>&1 || daemon -f wireplumber
fi
STARTEOF
}

# Check if a profile has PipeWire daemon startup
profile_has_pw_start() {
    for _f in $PROFILE_FILES; do
        [ -f "$_f" ] && grep -q 'daemon.*pipewire' "$_f" 2>/dev/null && echo "$_f" && return
    done
    return 1
}

# ════════════════════════════════════════════════════════════════════════════
#  CLI MODE
# ════════════════════════════════════════════════════════════════════════════
cli_mode() {
    ISSUES=0

    # ── Packages ────────────────────────────────────────────────────────────
    section "PipeWire — Packages"

    _missing=""
    for _pkg in pipewire wireplumber rtkit; do
        if pkg info "$_pkg" >/dev/null 2>&1; then
            ok "${_pkg} installed"
        else
            fail "${_pkg} not installed"
            _missing="${_missing} ${_pkg}"
            ISSUES=$((ISSUES + 1))
        fi
    done

    # pipewire-pulse may be a subpackage
    if pkg info pipewire-pulse >/dev/null 2>&1; then
        ok "pipewire-pulse installed"
    elif command -v pipewire-pulse >/dev/null 2>&1; then
        ok "pipewire-pulse available"
    else
        warn "pipewire-pulse not found (PulseAudio compat layer)"
        _missing="${_missing} pipewire-pulse"
        ISSUES=$((ISSUES + 1))
    fi

    if pkg info alsa-plugins >/dev/null 2>&1; then
        ok "alsa-plugins installed (ALSA→OSS bridge)"
    else
        warn "alsa-plugins not installed (needed for ALSA apps)"
        _missing="${_missing} alsa-plugins"
        ISSUES=$((ISSUES + 1))
    fi

    if [ -n "$_missing" ]; then
        if ask_yes "Install missing packages:${_missing}?"; then
            pkg install -y $_missing 2>&1 | tail -3
        fi
    fi

    # ── XDG_RUNTIME_DIR ─────────────────────────────────────────────────────
    section "PipeWire — Runtime Environment"

    # Check directory exists
    if [ -d "$XDG_DIR" ]; then
        ok "XDG_RUNTIME_DIR exists (${XDG_DIR})"
        # Check permissions
        _owner=$(stat -f '%u' "$XDG_DIR" 2>/dev/null || echo "?")
        if [ "$_owner" = "$PW_USER_UID" ]; then
            ok "  Owned by current user"
        else
            warn "  Owned by UID ${_owner} (expected ${PW_USER_UID})"
            ISSUES=$((ISSUES + 1))
        fi
    else
        fail "XDG_RUNTIME_DIR does not exist (${XDG_DIR})"
        ISSUES=$((ISSUES + 1))
        info "PipeWire will NOT start without this directory"
        if ask_yes "Create ${XDG_DIR}?"; then
            mkdir -p "$XDG_DIR"
            chmod 700 "$XDG_DIR"
            chown "${PW_USER_UID}" "$XDG_DIR" 2>/dev/null || true
            ok "Created"
        fi
    fi

    # Check env var is set in current shell
    if [ -n "${XDG_RUNTIME_DIR:-}" ]; then
        ok "XDG_RUNTIME_DIR set in current shell: ${XDG_RUNTIME_DIR}"
    else
        warn "XDG_RUNTIME_DIR not set in current shell"
        ISSUES=$((ISSUES + 1))
    fi

    if [ -n "${DBUS_SESSION_BUS_ADDRESS:-}" ]; then
        ok "DBUS_SESSION_BUS_ADDRESS set"
    else
        warn "DBUS_SESSION_BUS_ADDRESS not set in current shell"
        ISSUES=$((ISSUES + 1))
    fi

    # Check profile persistence
    _xdg_profile=$(profile_has_xdg || true)
    if [ -n "$_xdg_profile" ]; then
        ok "XDG_RUNTIME_DIR exported in $(basename "$_xdg_profile")"
    else
        fail "XDG_RUNTIME_DIR not exported in any profile script"
        ISSUES=$((ISSUES + 1))
        info "PipeWire needs this on every login (FreeBSD has no systemd to set it)"
        if ask_yes "Add env exports to ~/.profile?"; then
            env_block >> "${HOME}/.profile"
            ok "Added to ~/.profile"
        fi
    fi

    _dbus_profile=$(profile_has_dbus || true)
    if [ -n "$_dbus_profile" ]; then
        ok "DBUS_SESSION_BUS_ADDRESS exported in $(basename "$_dbus_profile")"
    else
        warn "DBUS_SESSION_BUS_ADDRESS not in any profile script"
        # May have been added with the XDG block above
        if ! profile_has_dbus >/dev/null 2>&1; then
            ISSUES=$((ISSUES + 1))
        fi
    fi

    # Check pam_xdg / seatd
    if grep -rq 'pam_xdg' /etc/pam.d/ 2>/dev/null; then
        ok "pam_xdg found in PAM config (auto-sets XDG_RUNTIME_DIR)"
    else
        info "pam_xdg not in PAM config (env vars must be set manually)"
    fi

    # ── Session startup ─────────────────────────────────────────────────────
    section "PipeWire — Session Startup (no systemd)"

    _pw_startup=$(profile_has_pw_start || true)
    if [ -n "$_pw_startup" ]; then
        ok "PipeWire daemon startup found in $(basename "$_pw_startup")"
    else
        # Check rc service
        _pw_rc=$(sysrc -n pipewire_enable 2>/dev/null || echo "")
        if [ "$_pw_rc" = "YES" ] || [ "$_pw_rc" = "yes" ]; then
            ok "pipewire_enable=YES in rc.conf (service mode)"
        else
            warn "No PipeWire autostart found"
            ISSUES=$((ISSUES + 1))
            info "FreeBSD has no systemd — PipeWire needs manual startup"

            _target="${HOME}/.xinitrc"
            [ ! -f "$_target" ] && _target="${HOME}/.profile"

            if ask_yes "Add daemon startup to $(basename "$_target")?"; then
                startup_block >> "$_target"
                ok "Added to $(basename "$_target")"
            fi
        fi
    fi

    # ── Drop-in configs ─────────────────────────────────────────────────────
    section "PipeWire — Configuration"

    if [ -d "$PW_DROPIN_DIR" ]; then
        _count=$(ls "$PW_DROPIN_DIR"/*.conf 2>/dev/null | wc -l | tr -d ' ')
        ok "User drop-in dir exists (${_count} file(s))"
        for _f in "$PW_DROPIN_DIR"/*.conf; do
            [ -f "$_f" ] && info "  $(basename "$_f")"
        done
    else
        info "No user drop-in dir (${PW_DROPIN_DIR})"
        info "Using system/upstream defaults"
    fi

    # Check latency config
    if [ -f "$PW_LATENCY_CONF" ]; then
        _q=$(pw_dropin_get "$PW_LATENCY_CONF" "default.clock.quantum")
        _r=$(pw_dropin_get "$PW_LATENCY_CONF" "default.clock.rate")
        ok "Latency drop-in exists"
        [ -n "$_q" ] && info "  Quantum: ${_q}"
        [ -n "$_r" ] && info "  Clock rate: ${_r}"
    else
        info "No latency drop-in (using PipeWire defaults: quantum=1024, rate=48000)"
    fi

    # ALSA drop-in
    _alsa_dropin="${PW_SYS_CONF}/pipewire.conf.d/alsa-default.conf"
    if [ -f "$_alsa_dropin" ]; then
        ok "ALSA drop-in exists (${_alsa_dropin})"
    else
        _alsa_user="${PW_DROPIN_DIR}/alsa-default.conf"
        if [ -f "$_alsa_user" ]; then
            ok "ALSA drop-in exists (user dir)"
        else
            warn "No ALSA drop-in found"
            info "ALSA apps may not work through PipeWire without it"
            ISSUES=$((ISSUES + 1))
        fi
    fi

    # ── Process status ──────────────────────────────────────────────────────
    section "PipeWire — Process Status"

    _all_ok=1
    for _proc in pipewire pipewire-pulse wireplumber; do
        if pgrep -x "$_proc" >/dev/null 2>&1; then
            _pid=$(pgrep -x "$_proc" | head -1)
            ok "${_proc} running (PID: ${_pid})"
        else
            warn "${_proc} not running"
            _all_ok=0
        fi
    done

    if [ "$_all_ok" -eq 0 ]; then
        if ask_yes "Start PipeWire session (pipewire + pipewire-pulse + wireplumber)?"; then
            # Ensure env is set for this invocation
            export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-${XDG_DIR}}"
            [ ! -d "$XDG_RUNTIME_DIR" ] && mkdir -p "$XDG_RUNTIME_DIR" && chmod 700 "$XDG_RUNTIME_DIR"

            for _proc in pipewire pipewire-pulse wireplumber; do
                if ! pgrep -x "$_proc" >/dev/null 2>&1; then
                    daemon -f "$_proc" 2>/dev/null && ok "Started ${_proc}" || fail "Failed to start ${_proc}"
                fi
            done
        fi
    fi

    # ── Summary ─────────────────────────────────────────────────────────────
    printf "\n"
    if [ "$ISSUES" -eq 0 ]; then
        ok "All checks passed."
    else
        info "${ISSUES} issue(s) found."
        [ "$MODE" = "dryrun" ] && info "Run without --dry-run to fix."
    fi
}

# ════════════════════════════════════════════════════════════════════════════
#  TUI MODE
# ════════════════════════════════════════════════════════════════════════════
tui_mode() {
    if ! command -v bsddialog >/dev/null 2>&1; then
        printf "Error: bsddialog not found. Install it or use FreeBSD 14+.\n" >&2
        exit 1
    fi

    _BT="PipeWire Configuration — FreeBSD $(uname -r)"

    # Load current values or defaults
    _quantum="1024"
    _min_quantum="32"
    _max_quantum="2048"
    _rate="48000"

    if [ -f "$PW_LATENCY_CONF" ]; then
        _v=$(pw_dropin_get "$PW_LATENCY_CONF" "default.clock.quantum");     [ -n "$_v" ] && _quantum="$_v"
        _v=$(pw_dropin_get "$PW_LATENCY_CONF" "default.clock.min-quantum"); [ -n "$_v" ] && _min_quantum="$_v"
        _v=$(pw_dropin_get "$PW_LATENCY_CONF" "default.clock.max-quantum"); [ -n "$_v" ] && _max_quantum="$_v"
        _v=$(pw_dropin_get "$PW_LATENCY_CONF" "default.clock.rate");        [ -n "$_v" ] && _rate="$_v"
    fi

    while true; do
        _running=""
        for _p in pipewire pipewire-pulse wireplumber; do
            if pgrep -x "$_p" >/dev/null 2>&1; then
                _running="${_running} ${_p}:✓"
            else
                _running="${_running} ${_p}:✗"
            fi
        done

        _choice=$(bsddialog \
            --backtitle "$_BT" \
            --title "PipeWire Settings" \
            --ok-label "Edit" \
            --cancel-label "Exit" \
            --menu "Drop-in: ${PW_LATENCY_CONF}\nProcesses:${_running}" 20 68 10 \
            quantum     "Clock quantum: ${_quantum}" \
            min_quantum "Min quantum: ${_min_quantum}" \
            max_quantum "Max quantum: ${_max_quantum}" \
            rate        "Clock rate: ${_rate} Hz" \
            apply       ">>> Save latency drop-in <<<" \
            env         "Check/fix environment setup" \
            startup     "Check/fix session startup" \
            restart     "Restart PipeWire session" \
            3>&1 1>&2 2>&3) || return

        case "$_choice" in
            quantum)
                _new=$(bsddialog --backtitle "$_BT" --title "Clock Quantum" \
                    --radiolist "Default buffer quantum (lower = less latency):" 16 55 7 \
                    "32"   "32 — Ultra low (may glitch)"  "$([ "$_quantum" = "32"   ] && echo on || echo off)" \
                    "64"   "64 — Very low"                "$([ "$_quantum" = "64"   ] && echo on || echo off)" \
                    "128"  "128 — Low latency"            "$([ "$_quantum" = "128"  ] && echo on || echo off)" \
                    "256"  "256 — Balanced"               "$([ "$_quantum" = "256"  ] && echo on || echo off)" \
                    "512"  "512 — Desktop"                "$([ "$_quantum" = "512"  ] && echo on || echo off)" \
                    "1024" "1024 — Safe default"           "$([ "$_quantum" = "1024" ] && echo on || echo off)" \
                    "2048" "2048 — Maximum stability"      "$([ "$_quantum" = "2048" ] && echo on || echo off)" \
                    3>&1 1>&2 2>&3) || continue
                _quantum="$_new"
                ;;
            min_quantum)
                _new=$(bsddialog --backtitle "$_BT" --title "Min Quantum" \
                    --radiolist "Minimum allowed quantum:" 14 50 5 \
                    "16"  "16"  "$([ "$_min_quantum" = "16"  ] && echo on || echo off)" \
                    "32"  "32"  "$([ "$_min_quantum" = "32"  ] && echo on || echo off)" \
                    "64"  "64"  "$([ "$_min_quantum" = "64"  ] && echo on || echo off)" \
                    "128" "128" "$([ "$_min_quantum" = "128" ] && echo on || echo off)" \
                    "256" "256" "$([ "$_min_quantum" = "256" ] && echo on || echo off)" \
                    3>&1 1>&2 2>&3) || continue
                _min_quantum="$_new"
                ;;
            max_quantum)
                _new=$(bsddialog --backtitle "$_BT" --title "Max Quantum" \
                    --radiolist "Maximum allowed quantum:" 14 50 5 \
                    "512"  "512"  "$([ "$_max_quantum" = "512"  ] && echo on || echo off)" \
                    "1024" "1024" "$([ "$_max_quantum" = "1024" ] && echo on || echo off)" \
                    "2048" "2048" "$([ "$_max_quantum" = "2048" ] && echo on || echo off)" \
                    "4096" "4096" "$([ "$_max_quantum" = "4096" ] && echo on || echo off)" \
                    "8192" "8192" "$([ "$_max_quantum" = "8192" ] && echo on || echo off)" \
                    3>&1 1>&2 2>&3) || continue
                _max_quantum="$_new"
                ;;
            rate)
                _new=$(bsddialog --backtitle "$_BT" --title "Clock Rate" \
                    --radiolist "PipeWire clock rate (Hz):" 14 50 5 \
                    "44100"  "44.1 kHz (CD)"      "$([ "$_rate" = "44100"  ] && echo on || echo off)" \
                    "48000"  "48 kHz (standard)"  "$([ "$_rate" = "48000"  ] && echo on || echo off)" \
                    "96000"  "96 kHz (studio)"    "$([ "$_rate" = "96000"  ] && echo on || echo off)" \
                    "192000" "192 kHz (high-res)" "$([ "$_rate" = "192000" ] && echo on || echo off)" \
                    3>&1 1>&2 2>&3) || continue
                _rate="$_new"
                ;;
            apply)
                bsddialog --backtitle "$_BT" --title "Save Drop-in" \
                    --yesno "Write latency config:\n\n  quantum=${_quantum}\n  min-quantum=${_min_quantum}\n  max-quantum=${_max_quantum}\n  rate=${_rate}\n\nTo: ${PW_LATENCY_CONF}" 14 60 || continue
                pw_write_latency_conf "$_quantum" "$_min_quantum" "$_max_quantum" "$_rate"
                bsddialog --backtitle "$_BT" --title "Saved" \
                    --yesno "Drop-in written.\n\nRestart PipeWire to apply?" 8 45
                [ $? -eq 0 ] && _tui_restart
                ;;
            env)
                _tui_check_env
                ;;
            startup)
                _tui_check_startup
                ;;
            restart)
                _tui_restart
                ;;
        esac
    done
}

_tui_restart() {
    export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-${XDG_DIR}}"
    [ ! -d "$XDG_RUNTIME_DIR" ] && mkdir -p "$XDG_RUNTIME_DIR" && chmod 700 "$XDG_RUNTIME_DIR"

    # Kill existing
    for _p in wireplumber pipewire-pulse pipewire; do
        pkill -x "$_p" 2>/dev/null || true
    done
    sleep 1

    # Start fresh
    _result=""
    for _p in pipewire pipewire-pulse wireplumber; do
        if daemon -f "$_p" 2>/dev/null; then
            _result="${_result}\n  ✓ ${_p} started"
        else
            _result="${_result}\n  ✗ ${_p} failed"
        fi
    done
    sleep 1

    bsddialog --backtitle "PipeWire" --title "Restart" \
        --msgbox "Results:${_result}" 10 45
}

_tui_check_env() {
    _msg=""

    if [ -d "$XDG_DIR" ]; then
        _msg="${_msg}\n✓ ${XDG_DIR} exists"
    else
        _msg="${_msg}\n✗ ${XDG_DIR} missing"
    fi

    if [ -n "${XDG_RUNTIME_DIR:-}" ]; then
        _msg="${_msg}\n✓ XDG_RUNTIME_DIR set"
    else
        _msg="${_msg}\n✗ XDG_RUNTIME_DIR not set"
    fi

    if [ -n "${DBUS_SESSION_BUS_ADDRESS:-}" ]; then
        _msg="${_msg}\n✓ DBUS_SESSION_BUS_ADDRESS set"
    else
        _msg="${_msg}\n✗ DBUS_SESSION_BUS_ADDRESS not set"
    fi

    _xdg_where=$(profile_has_xdg || echo "")
    if [ -n "$_xdg_where" ]; then
        _msg="${_msg}\n✓ XDG export in $(basename "$_xdg_where")"
    else
        _msg="${_msg}\n✗ XDG export not in any profile"
    fi

    bsddialog --backtitle "PipeWire" --title "Environment Check" \
        --yesno "${_msg}\n\nAdd env exports to ~/.profile if missing?" 14 60

    if [ $? -eq 0 ]; then
        _xdg_check=$(profile_has_xdg || true)
        if [ -z "$_xdg_check" ]; then
            env_block >> "${HOME}/.profile"
        fi
        bsddialog --backtitle "PipeWire" --title "Done" --msgbox "Profile updated." 7 35
    fi
}

_tui_check_startup() {
    _msg=""
    _pw_where=$(profile_has_pw_start || echo "")
    if [ -n "$_pw_where" ]; then
        _msg="✓ PipeWire startup found in $(basename "$_pw_where")"
    else
        _pw_rc=$(sysrc -n pipewire_enable 2>/dev/null || echo "")
        if [ "$_pw_rc" = "YES" ] || [ "$_pw_rc" = "yes" ]; then
            _msg="✓ pipewire_enable=YES in rc.conf"
        else
            _msg="✗ No PipeWire autostart configured"
        fi
    fi

    _target="${HOME}/.xinitrc"
    [ ! -f "$_target" ] && _target="${HOME}/.profile"

    bsddialog --backtitle "PipeWire" --title "Session Startup" \
        --yesno "${_msg}\n\nAdd daemon startup to $(basename "$_target")?" 10 60

    if [ $? -eq 0 ]; then
        _check=$(profile_has_pw_start || true)
        if [ -z "$_check" ]; then
            startup_block >> "$_target"
        fi
        bsddialog --backtitle "PipeWire" --title "Done" --msgbox "Startup added." 7 35
    fi
}

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#                              MAIN
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

if [ "$MODE" = "tui" ]; then
    tui_mode
else
    cli_mode
fi
